
server:
  port: 9180
logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: workflow-engine-bpmn
  datasource:
    process-engine:
      url: jdbc:postgresql://localhost:5432/uit-bpmn-activiti
      username: postgres
      password: Password123
      driver-class-name: org.postgresql.Driver
    dpl-platform:
      url: jdbc:postgresql://localhost:5432/uit-dpl-platform
      username: postgres
      password: Password123
      driver-class-name: org.postgresql.Driver
  jpa:
    process-engine:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    dpl-platform:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
flyway:
  enabled: true
  locations: classpath:db/migration
